server:
  port: 8080

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: true
    encoding: UTF-8
    mode: HTML5
    cache: false
 #static
  resources:
    add-mappings: true
    chain:
      cache: true
      enabled: true
      compressed: true
      html-application-cache: true
    static-locations: classpath:/static/
    cache:
     period: 3600
  #rabbitmq
  rabbitmq:
   host: 47.101.133.15
   port: 5672
   username: guest
   password: guest
   virtual-host: /
   listener:
     simple:
       concurrency: 10
       max-concurrency: 10
       prefetch: 1
       auto-startup: true
       default-requeue-rejected: true
   template:
     retry:
       enabled: true
       initial-interval: 1000
       max-attempts: 3
       max-interval: 10000
       multiplier: 1.0
  #连接池
  datasource:
   username: root
   password: 123456-abc
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://47.101.133.15:3306/seckill?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

#static
redis:
  host: 47.101.133.15 #localhost
  port: 6379
  timeout: 10
  maxActive: 1500
  maxIdle: 500
  maxWait: 500
  password: 123456

# mybatis
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: org.ct.seckill.domain
  configuration:
    map-underscore-to-camel-case: true

# 日志
logging:
  level:
    org.ct.seckill.* : debug
sOfServiceUrl: http://www.baidu.com
